// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ZendeskApiCore.Models;

public partial class ESCORIALContext : DbContext
{
    public ESCORIALContext()
    {
    }

    public ESCORIALContext(DbContextOptions<ESCORIALContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Login> Login { get; set; }

    public virtual DbSet<Problema> Problemas { get; set; }

    public virtual DbSet<Provincia> Provincias { get; set; }

    public virtual DbSet<Tecnico> Tecnicos { get; set; }

    public virtual DbSet<TipoTecnico> TiposTecnico { get; set; }

    public virtual DbSet<ItemReclamoWebZendesk> ItemsReclamoWebZendesk { get; set; }
    

    public virtual DbSet<Producto> Productos { get; set; }

    public virtual DbSet<ReclamoWebZendesk> ReclamosWebZendesk { get; set; }
    
    public virtual DbSet<TipoProducto> TiposProducto { get; set; }
    
    public virtual DbSet<ItemTipoClasificador> ItemsTipoClasificador { get; set; }
    
    public virtual DbSet<Segmento> Segmentos { get; set; }
    
    
    
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) {}

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasPostgresExtension("fuzzystrmatch")
            .HasPostgresExtension("hstore")
            .HasPostgresExtension("ltree")
            .HasPostgresExtension("pg_stat_statements")
            .HasPostgresExtension("pgstattuple")
            .HasPostgresExtension("unaccent");

        modelBuilder.Entity<Login>(entity =>
        {
            entity.ToView("api_login", "web");
        });

        modelBuilder.Entity<Problema>(entity =>
        {
            entity.ToView("api_zendeskreclamosweb_problemas", "web");
        });

        modelBuilder.Entity<Provincia>(entity =>
        {
            entity.ToView("api_zendeskreclamosweb_provincias", "web");
        });

        modelBuilder.Entity<Tecnico>(entity =>
        {
            entity.ToView("api_zendeskreclamosweb_tecnicos", "web");
        });

        modelBuilder.Entity<TipoTecnico>(entity =>
        {
            entity.ToView("api_zendeskreclamosweb_tipostecnico", "web");
        });
        
        modelBuilder.Entity<TipoProducto>(entity =>
        {
            entity.ToView("api_zendeskreclamosweb_tiposproducto", "web");
        });

        modelBuilder.Entity<ItemTipoClasificador>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("itemtipoclasificador_pkey"); 
        });

        modelBuilder.Entity<Segmento>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("segmento_pkey");
        });

        modelBuilder.Entity<ItemReclamoWebZendesk>(entity =>
        {
            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .UseIdentityAlwaysColumn();
        });

        modelBuilder.Entity<Producto>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("producto_pkey");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.ActiveStatus).HasDefaultValue(0);
            entity.Property(e => e.Alto).HasDefaultValueSql("0.0");
            entity.Property(e => e.Ancho).HasDefaultValueSql("0.0");
            entity.Property(e => e.BienUso).HasDefaultValue(false);
            entity.Property(e => e.CalculoExInoLineal).HasDefaultValue(false);
            entity.Property(e => e.Cantidad).HasDefaultValue(0);
            entity.Property(e => e.ConcatCodProd).HasDefaultValue(false);
            entity.Property(e => e.CreacionCodAlt).HasDefaultValue(false);
            entity.Property(e => e.EsMultiploDeBultos).HasDefaultValue(false);
            entity.Property(e => e.Espesor).HasDefaultValueSql("0.0");
            entity.Property(e => e.ExistenciaObligatoria).HasDefaultValue(false);
            entity.Property(e => e.ExistenciaObligatoriaNl).HasDefaultValue(false);
            entity.Property(e => e.ExplotaPropiedades).HasDefaultValue(false);
            entity.Property(e => e.ExplotaSerieEnInventario).HasDefaultValue(false);
            entity.Property(e => e.Kit).HasDefaultValue(false);
            entity.Property(e => e.MontoProducto).HasDefaultValueSql("0.0");
            entity.Property(e => e.MontoTotal).HasDefaultValueSql("0.0");
            entity.Property(e => e.Peso).HasDefaultValueSql("0.0");
            entity.Property(e => e.PorcentajeCategoria).HasDefaultValueSql("0.0");
            entity.Property(e => e.PorcentajeReposicion).HasDefaultValueSql("0.0");
            entity.Property(e => e.PuntoPedido).HasDefaultValueSql("0.0");
            entity.Property(e => e.StockMaximo).HasDefaultValueSql("0.0");
            entity.Property(e => e.StockMinimo).HasDefaultValueSql("0.0");
            entity.Property(e => e.StockOptimo).HasDefaultValueSql("0.0");
            entity.Property(e => e.StockSeguridad).HasDefaultValueSql("0.0");
            entity.Property(e => e.UnidadesPorBulto).HasDefaultValueSql("0.0");
            entity.Property(e => e.UnidMinimComer).HasDefaultValueSql("0.0");
            entity.Property(e => e.UtilCnlTotalItem).HasDefaultValue(false);
            entity.Property(e => e.UtilizaCantidadNoLineal).HasDefaultValue(false);
            entity.Property(e => e.UtilizaSerieDetallada).HasDefaultValue(false);
            entity.Property(e => e.Volumen).HasDefaultValueSql("0.0");
        });

        modelBuilder.Entity<ReclamoWebZendesk>(entity =>
        {
            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .UseIdentityAlwaysColumn();
        });
        
        modelBuilder.HasSequence("aux_suceso_inc_seq");
        modelBuilder.HasSequence("hibernate_sequence", "web");

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}