// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ZendeskApiCore.Models;

[Table("items_reclamowebzendesk", Schema = "web")]
public partial class ItemReclamoWebZendesk
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("serie")]
    [StringLength(200)]
    public string Serie { get; set; }

    [Column("articulo_id")]
    [StringLength(60)]
    public string ArticuloId { get; set; }

    [Column("descripcion")]
    [StringLength(255)]
    public string Descripcion { get; set; }

    [Column("problema")]
    [StringLength(255)]
    public string Problema { get; set; }

    [Column("reclamo_id")]
    [StringLength(60)]
    public string ReclamoId { get; set; }
}