// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ZendeskApiCore.Models;

[Keyless]
public partial class ProblemaDto
{
    [Column("id")]
    public Guid? Id { get; set; }

    [Column("codigo")]
    [StringLength(60)]
    public string Codigo { get; set; }

    [Column("nombre")]
    [StringLength(120)]
    public string Nombre { get; set; }
    [NotMapped]
    public TipoProducto TipoProducto { get; set; }
}