// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ZendeskApiCore.Models;

[Table("producto")]
[Index("BoPlaceId", Name = "idx00344081")]
[Index("Codigo", Name = "idx00344082")]
[Index("RubroId", Name = "idx00344083")]
public partial class Producto
{
    [Key] [Column("id")] 
    public Guid Id { get; set; }

    [Column("activestatus")] 
    public int? ActiveStatus { get; set; }

    [Column("checksoptimisticupdates")]
    [StringLength(40)]
    public string ChecksOptimisticUpdates { get; set; }

    [Column("codigo")] 
    [StringLength(30)] 
    public string Codigo { get; set; }

    [Column("segmento_id")] 
    public Guid? SegmentoId { get; set; }

    [Column("descripcion")]
    [StringLength(150)]
    public string Descripcion { get; set; }

    [Column("usuario")] 
    [StringLength(30)] 
    public string Usuario { get; set; }

    [Column("momento")] 
    [StringLength(17)] 
    public string Momento { get; set; }

    [Column("catalogo_id")] 
    public Guid? CatalogoId { get; set; }

    [Column("itemcatalogo_id")] 
    public Guid? ItemCatalogoId { get; set; }

    [Column("codigosalternativos_id")] 
    public Guid? CodigosAlternativosId { get; set; }

    [Column("detalleproveedores_id")] 
    public Guid? DetalleProveedoresId { get; set; }

    [Column("listacosto_id")] 
    public Guid? ListaCostoId { get; set; }

    [Column("grupocomposicion_id")] 
    public Guid? GrupoComposicionId { get; set; }

    [Column("rubro_id")] 
    public Guid? RubroId { get; set; }

    [Column("posicionadorimpuestos_id")] 
    public Guid? PosicionadorImpuestosId { get; set; }

    [Column("partidapresup_id")] 
    public Guid? PartidaPresupId { get; set; }

    [Column("tipodistribuciondefault_id")] 
    public Guid? TipoDistribucionDefaultId { get; set; }

    [Column("composicion_id")] 
    public Guid? ComposicionId { get; set; }

    [Column("clasificacioncosto_id")] 
    public Guid? ClasificacionCostoId { get; set; }

    [Column("boextension_id")] 
    public Guid? BoExtensionId { get; set; }

    [Column("componentecosto_id")] 
    public Guid? ComponenteCostoId { get; set; }

    [Column("definicioncompcosto_id")] 
    public Guid? DefinicionCompCostoId { get; set; }

    [Column("tipoobjetoestatico_id")] 
    public Guid? TipoObjetoEstaticoId { get; set; }

    [Column("flag_id")] 
    public Guid? FlagId { get; set; }

    [Column("transicion_id")] 
    public Guid? TransicionId { get; set; }

    [Column("centrocostos_id")] 
    public Guid? CentroCostosId { get; set; }

    [Column("centroscostosasociados_id")] 
    public Guid? CentrosCostosAsociadosId { get; set; }

    [Column("conceptooaf_id")] 
    public Guid? ConceptoOafId { get; set; }

    [Column("unidadoperativa_id")] 
    public Guid? UnidadOperativaId { get; set; }

    [Column("distribucionproveedores_id")] 
    public Guid? DistribucionProveedoresId { get; set; }

    [Column("partidapresupventas_id")] 
    public Guid? PartidaPresupVentasId { get; set; }

    [Column("itemsesquemaoperativo_id")] 
    public Guid? ItemsEsquemaOperativoId { get; set; }

    [Column("bocsf_id")] 
    public Guid? BoCsfId { get; set; }

    [Column("numerador_id")] 
    public Guid? NumeradorId { get; set; }

    [Column("relacionimpproductoservicio_id")]
    public Guid? RelacionImpProductoServicioId { get; set; }

    [Column("condicion_id")] 
    public Guid? CondicionId { get; set; }

    [Column("fechavencimientocondicion")]
    [StringLength(8)]
    public string FechaVencimientoCondicion { get; set; }

    [Column("ultimamodificacion")]
    [StringLength(17)]
    public string UltimaModificacion { get; set; }

    [Column("bo_place_id")] 
    public Guid? BoPlaceId { get; set; }

    [Column("bo_owner_id")] 
    public Guid? BoOwnerId { get; set; }

    [Column("unidadmedida_id")] 
    public Guid? UnidadMedidaId { get; set; }

    [Column("unidadmedidanolineal_id")] 
    public Guid? UnidadMedidaNoLinealId { get; set; }

    [Column("unidadesmedidaparticulares_id")]
    public Guid? UnidadesMedidaParticularesId { get; set; }

    [Column("unidminimcomer")]
    [Precision(22, 10)]
    public decimal? UnidMinimComer { get; set; }

    [Column("equivalenciasparticulares_id")]
    public Guid? EquivalenciasParticularesId { get; set; }

    [Column("unidadesdeexpresion_id")] 
    public Guid? UnidadesDeExpresionId { get; set; }

    [Column("tipoextraccion_id")] 
    public Guid? TipoExtraccionId { get; set; }

    [Column("grupospertenecia_id")] 
    public Guid? GruposPerteneciaId { get; set; }

    [Column("datoscomplementarios_id")] 
    public Guid? DatosComplementariosId { get; set; }

    [Column("compania_id")] 
    public Guid? CompaniaId { get; set; }

    [Column("atributosfusion_id")] 
    public Guid? AtributosFusionId { get; set; }

    [Column("existenciaobligatoria")] 
    public bool? ExistenciaObligatoria { get; set; }

    [Column("unidadesporbulto")]
    [Precision(22, 10)]
    public decimal? UnidadesPorBulto { get; set; }

    [Column("esmultiplodebultos")] 
    public bool? EsMultiploDeBultos { get; set; }

    [Column("configuradorimportacion_id")] 
    public Guid? ConfiguradorImportacionId { get; set; }

    [Column("external_id")]
    [StringLength(10)]
    public string ExternalId { get; set; }

    [Column("utilizacantidadnolineal")] 
    public bool? UtilizaCantidadNoLineal { get; set; }

    [Column("equivalenciasparticulnoli_id")]
    public Guid? EquivalenciasParticulNoLiId { get; set; }

    [Column("unidadesmedidaparticulnoli_id")]
    public Guid? UnidadesMedidaParticulNoLiId { get; set; }

    [Column("unidadesdeexpresionnoli_id")] 
    public Guid? UnidadesDeExpresionNoLiId { get; set; }

    [Column("proveedores_id")] 
    public Guid? ProveedoresId { get; set; }

    [Column("existenciaobligatorianl")] 
    public bool? ExistenciaObligatoriaNl { get; set; }

    [Column("calculoexinolineal")] 
    public bool? CalculoExInoLineal { get; set; }

    [Column("tolerancia_id")] 
    public Guid? ToleranciaId { get; set; }

    [Column("numeradoresserie_id")] 
    public Guid? NumeradoresSerieId { get; set; }

    [Column("explotaserieeninventario")] 
    public bool? ExplotaSerieEnInventario { get; set; }

    [Column("numeradoreslote_id")] 
    public Guid? NumeradoresLoteId { get; set; }

    [Column("numeradoresdespacho_id")] 
    public Guid? NumeradoresDespachoId { get; set; }

    [Column("peso")] 
    [Precision(22, 10)] 
    public decimal? Peso { get; set; }

    [Column("volumen")]
    [Precision(22, 10)]
    public decimal? Volumen { get; set; }

    [Column("bienuso")] 
    public bool? BienUso { get; set; }

    [Column("stockminimo")]
    [Precision(22, 10)]
    public decimal? StockMinimo { get; set; }

    [Column("puntopedido")]
    [Precision(22, 10)]
    public decimal? PuntoPedido { get; set; }

    [Column("stockseguridad")]
    [Precision(22, 10)]
    public decimal? StockSeguridad { get; set; }

    [Column("clientes_id")] 
    public Guid? ClientesId { get; set; }

    [Column("descriptor_id")] 
    public Guid? DescriptorId { get; set; }

    [Column("especificacionbase_id")] 
    public Guid? EspecificacionBaseId { get; set; }

    [Column("especificaciones_id")] 
    public Guid? EspecificacionesId { get; set; }

    [Column("explotapropiedades")] 
    public bool? ExplotaPropiedades { get; set; }

    [Column("productossustitutos_id")] 
    public Guid? ProductosSustitutosId { get; set; }

    [Column("cantidad")] 
    public int? Cantidad { get; set; }

    [Column("kit")] 
    public bool? Kit { get; set; }

    [Column("stockmaximo")]
    [Precision(22, 10)]
    public decimal? StockMaximo { get; set; }

    [Column("stockoptimo")]
    [Precision(22, 10)]
    public decimal? StockOptimo { get; set; }

    [Column("alto")] 
    [Precision(22, 10)] 
    public decimal? Alto { get; set; }

    [Column("unidadmedidaalto_id")] 
    public Guid? UnidadMedidaAltoId { get; set; }

    [Column("ancho")] 
    [Precision(22, 10)] 
    public decimal? Ancho { get; set; }

    [Column("unidadmedidaancho_id")] 
    public Guid? UnidadMedidaAnchoId { get; set; }

    [Column("espesor")]
    [Precision(22, 10)]
    public decimal? Espesor { get; set; }

    [Column("unidadmedidaespesor_id")] 
    public Guid? UnidadMedidaEspesorId { get; set; }

    [Column("unidadmedidavolumen_id")] 
    public Guid? UnidadMedidaVolumenId { get; set; }

    [Column("scriptpolinomicocosto_id")] 
    public Guid? ScriptPolinomicoCostoId { get; set; }

    [Column("envasepredeterminado_id")] 
    public Guid? EnvasePredeterminadoId { get; set; }

    [Column("envasespermitidos_id")] 
    public Guid? EnvasesPermitidosId { get; set; }

    [Column("lineas_id")] 
    public Guid? LineasId { get; set; }

    [Column("lineascodigos")]
    [StringLength(240)]
    public string LineasCodigos { get; set; }

    [Column("utilcnltotalitem")] 
    public bool? UtilCnlTotalItem { get; set; }

    [Column("dimensiones_id")] 
    public Guid? DimensionesId { get; set; }

    [Column("tipoamortizacion_id")] 
    public Guid? TipoAmortizacionId { get; set; }

    [Column("porcentajereposicion")]
    [Precision(22, 10)]
    public decimal? PorcentajeReposicion { get; set; }

    [Column("cuentascontables_id")] 
    public Guid? CuentasContablesId { get; set; }

    [Column("cuentascontables2_id")] 
    public Guid? CuentasContables2Id { get; set; }

    [Column("cuentascontables3_id")] 
    public Guid? CuentasContables3Id { get; set; }

    [Column("cuentascontables4_id")] 
    public Guid? CuentasContables4Id { get; set; }

    [Column("cuentascontables5_id")] 
    public Guid? CuentasContables5Id { get; set; }

    [Column("cuentascontables6_id")] 
    public Guid? CuentasContables6Id { get; set; }

    [Column("cuentascontables7_id")] 
    public Guid? CuentasContables7Id { get; set; }

    [Column("cuentascontables8_id")] 
    public Guid? CuentasContables8Id { get; set; }

    [Column("cuentascontables9_id")] 
    public Guid? CuentasContables9Id { get; set; }

    [Column("cuentascontables10_id")] 
    public Guid? CuentasContables10Id { get; set; }

    [Column("svg")] 
    public string Svg { get; set; }

    [Column("numeradorescodalt_id")] 
    public Guid? NumeradoresCodAltId { get; set; }

    [Column("creacioncodalt")] 
    public bool? CreacionCodAlt { get; set; }

    [Column("concatcodprod")] 
    public bool? ConcatCodProd { get; set; }

    [Column("categoria")]
    [StringLength(10)]
    public string Categoria { get; set; }

    [Column("cateant")] 
    [StringLength(10)] 
    string CateAnt { get; set; }

    [Column("montoproducto")]
    [Precision(22, 10)]
    public decimal? MontoProducto { get; set; }

    [Column("montototal")]
    [Precision(22, 10)]
    public decimal? MontoTotal { get; set; }

    [Column("porcentajecategoria")]
    [Precision(22, 10)]
    public decimal? PorcentajeCategoria { get; set; }

    [Column("fechacategoria")]
    [StringLength(17)]
    public string FechaCategoria { get; set; }

    [Column("utilizaseriedetallada")] 
    public bool? UtilizaSerieDetallada { get; set; }
}