// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ZendeskApiCore.Models;

[Keyless]
public partial class Provincia
{
    [Column("id")]
    public Guid? Id { get; set; }

    [Column("nombre")]
    [StringLength(40)]
    public string Nombre { get; set; }
}