// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ZendeskApiCore.Models;

[Table("reclamowebzendesk", Schema = "web")]
public partial class ReclamoWebZendesk
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("apynom")]
    [StringLength(200)]
    public string ApellidoNombre { get; set; }

    [Column("dni")]
    [StringLength(50)]
    public string Dni { get; set; }

    [Column("direccion")]
    [StringLength(200)]
    public string Direccion { get; set; }

    [Column("entre_calles")]
    [StringLength(200)]
    public string EntreCalles { get; set; }

    [Column("localidad_id")]
    [StringLength(200)]
    public string LocalidadId { get; set; }

    [Column("codpostal")]
    [StringLength(50)]
    public string CodigoPostal { get; set; }

    [Column("mail")]
    [StringLength(200)]
    public string Mail { get; set; }

    [Column("telefonos")]
    [StringLength(100)]
    public string Telefonos { get; set; }

    [Column("tecnico_tipo_id")]
    [StringLength(60)]
    public string TecnicoTipoId { get; set; }

    [Column("tecnico_id")]
    [StringLength(60)]
    public string TecnicoId { get; set; }

    [Column("producto_tipo_id")]
    [StringLength(60)]
    public string ProductoTipoId { get; set; }

    [Column("producto_id")]
    [StringLength(60)]
    public string ProductoId { get; set; }

    [Column("created_at", TypeName = "timestamp without time zone")]
    public DateTime? CreatedAt { get; set; }

    [Column("user_created")]
    [StringLength(60)]
    public string UserCreated { get; set; }

    [Column("garantia")]
    public bool? Garantia { get; set; }

    [Column("casavendedora")]
    [StringLength(200)]
    public string CasaVendedora { get; set; }

    [Column("cargado")]
    public bool? Cargado { get; set; }

    [Column("fechahora_ingreso_pagina", TypeName = "timestamp without time zone")]
    public DateTime? FechaHoraIngresoPagina { get; set; }

    [Column("fechahora_ingreso_calipso", TypeName = "timestamp without time zone")]
    public DateTime? FechaHoraIngresoCalipso { get; set; }

    [Column("numeroreclamo")]
    [StringLength(60)]
    public string NumeroReclamo { get; set; }
    [NotMapped]
    public List<ItemReclamoWebZendesk> ItemsReclamoWebZendesk { get; set; }
    [NotMapped]
    public TrReclamoDto ReclamoAsociado { get; set; } = new TrReclamoDto();

}